<a href="https://colab.research.google.com/github/Caarevalor/Python_Datascience_Notebooks/blob/main/Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Quiz Week 1


In [ ]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [ ]:
##2 
import numpy as np
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)
print(a1)
print(a2)
print(a3)
print(a4)
print(a5)
print(a4.ndim)

[0.04708498 0.88291075 0.62932622 0.83553084]
[[0.85629311]
 [0.24130359]
 [0.99695599]
 [0.99874912]]
[[1 2 3 4]]
[1 2 3]
[1. 2. 3. 4.]
1


In [ ]:
#3
import numpy as np
old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0
print(old)

[[0 0 1]
 [1 1 1]]


In [ ]:
#4
import re
s = 'ACBCAC'
re.findall('^AC',s)

['BC']

In [ ]:
import re

s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

0


In [ ]:
text='Office of Research Administration: (734) 647-6333 | 4325 North Quad Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205 Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500 Office of the Dean: (734) 647-3576 | 4322 North Quad UMSI Engagement Center: (734) 763-1251 | 777 North University Faculty Adminstrative Support Staff: (734) 764-9376 | 4322 North Quad'
#re.findall("\d{3}[-]\d{3}[-]\d{4}",text)
#re.findall("[(]\d{3}[)]\d{3}[-]\d{4}",text)
re.findall("[(]\d{3}[)]\s\d{3}[-]\d{4}",text)
#numbers= re.findall('\d{3}\s\d{3}[-]\d{4}',text)
#re.findall("\d{3}\s\d{3}[-]\d{4}",text)

['(734) 647-6333',
 '(734) 647-8044',
 '(734) 763-2285',
 '(734) 647-3576',
 '(734) 763-1251',
 '(734) 764-9376']

In [ ]:
text2='I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'
re.findall("(?<=[https]:\/\/)([A-Za-z0-9.]*)",text2)
#re.findall("(?<=https:\/\/)([A-Za-z0-9.]*)",text2) ## no tiene corchetes coge solo si esta escrito https
#re.findall("(?<=https:\/\/)([A-Za-z0-9]*)",text2) #le quita el punto, solo me da e nombre
#re.findall("(?<=https:\/\/)([.]*)",text2)

['google.com', 'www.baidu.com']

In [ ]:
text3=r'''Everyone has the following fundamental freedoms:
(a) freedom of conscience and religion;
(b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
(c) freedom of peaceful assembly; and
(d) freedom of association.
'''
import re

#pattern = '\(.\) '
#pattern = '(.) '
pattern = '[a-d]'
print(len(re.findall(pattern,text3)))

40
